export default function About() {
    return (
      <>
        <Head>
          <title>About Me</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} `}>
           Additional Info on this page along with contact info and other things
        </main>
      </>
    );
  }