export default function Experiences() {
    return (
      <>
        <Head>
          <title>Experiences</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
            Experience Info on this page
          
        </main>
      </>
    );
  }